export const markets = [
  ["US", "United States"],
  ["GB", "United Kingdom"],
  ["CA", "Canada"],
  ["AU", "Australia"],
  ["IL", "Israel"],
  ["DE", "Germany"],
  ["FR", "France"],
  ["ES", "Spain"],
  ["IT", "Italy"],
  ["NL", "Netherlands"],
  ["SE", "Sweden"],
  ["NO", "Norway"],
  ["DK", "Denmark"],
  ["FI", "Finland"],
  ["CH", "Switzerland"],
  ["AT", "Austria"],
  ["BE", "Belgium"],
  ["IE", "Ireland"],
  ["PT", "Portugal"],
  ["PL", "Poland"],
  ["CZ", "Czechia"],
  ["RO", "Romania"],
  ["UA", "Ukraine"],
  ["TR", "Türkiye"],
  ["JP", "Japan"],
  ["KR", "South Korea"],
  ["CN", "China mainland"],
  ["HK", "Hong Kong"],
  ["TW", "Taiwan"],
  ["IN", "India"],
  ["SG", "Singapore"],
  ["MY", "Malaysia"],
  ["ID", "Indonesia"],
  ["TH", "Thailand"],
  ["VN", "Vietnam"],
  ["PH", "Philippines"],
  ["NZ", "New Zealand"],
  ["BR", "Brazil"],
  ["MX", "Mexico"],
  ["AR", "Argentina"],
  ["CL", "Chile"],
  ["CO", "Colombia"],
  ["PE", "Peru"],
  ["ZA", "South Africa"],
  ["AE", "United Arab Emirates"],
  ["SA", "Saudi Arabia"],
  ["EG", "Egypt"],
] as const;
export type Store = "iphone" | "ipad" | "mac";
export const stores: Record<Store, string> = {
  iphone: "iPhone App Store",
  ipad: "iPad App Store",
  mac: "Mac App Store",
};
export function flag(code: string) {
  return String.fromCodePoint(
    ...[...code].map((c) => 127397 + c.charCodeAt(0)),
  );
}
